Repository jdbi/jdbi, pull requests merged in 2018-04, with the labels that each got.

#1064 ResultProducers: add option to suppress exception if there's no result set
  RELEASE_NOTES
  core/src/main/java/org/jdbi/v3/core/result/EmptyResultSet.java
  core/src/main/java/org/jdbi/v3/core/result/ResultProducers.java
  core/src/main/java/org/jdbi/v3/core/statement/PreparedBatch.java
  core/src/main/java/org/jdbi/v3/core/statement/Query.java
  core/src/test/java/org/jdbi/v3/core/statement/TestStatements.java
Labels: feature

#1066 Support SQL Object default methods in JDK9+
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/DefaultMethodHandler.java
Labels: improvement

#1067 Fix docs that still refer to now-removed LinkedHashMapRowReducer.of() method
  core/src/test/java/org/jdbi/v3/core/result/TestReducing.java
  docs/src/adoc/index.adoc
Labels: doc

#1084 fix #1043
  core/src/main/java/org/jdbi/v3/core/statement/PreparedBatch.java
Labels: bug

#1091 Test registered DAO with generic parameter and returned collection
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestRegisteredGenericReturnAndParam.java
Labels: improvement

#1097 Remove NOTICE file that doesn't seem particularly informative
  NOTICE
Labels: cleanup

#1098 tidy up build scripts
  .travis.yml
  src/build/ci-code-style.sh
  src/build/ci-doc.sh
  src/build/ci-install.sh
  src/build/ci-pre-install.sh
  src/build/ci-test.sh
Labels: cleanup

#1093 Add a test to show jsonb query '?' can be escaped as '??' and work
  docs/src/adoc/index.adoc
  postgres/src/test/java/org/jdbi/v3/postgres/TestJsonOperator.java
Labels: doc, improvement

#1104 Update SQL parsers to treat `??` as a literal instead of positional parameters
  core/src/main/antlr3/org/jdbi/v3/core/internal/lexer/ColonStatementLexer.g
  core/src/main/antlr3/org/jdbi/v3/core/internal/lexer/HashStatementLexer.g
  core/src/test/java/org/jdbi/v3/core/statement/TestColonPrefixSqlParser.java
  core/src/test/java/org/jdbi/v3/core/statement/TestDefinedAttributeTemplateEngine.java
  core/src/test/java/org/jdbi/v3/core/statement/TestHashPrefixSqlParser.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestJsonOperator.java
  postgres/src/test/java/org/jdbi/v3/sqlobject/TestJsonOperator.java
Labels: bug
