Repository jdbi/jdbi, pull requests merged in 2018-12, with the labels that each got.

#1326 Allow instantiation of ParsedSql and ParsedParameters
  core/src/main/java/org/jdbi/v3/core/statement/ParsedParameters.java
  core/src/main/java/org/jdbi/v3/core/statement/ParsedSql.java
  core/src/test/java/org/jdbi/v3/core/statement/TestParsedParameters.java
  core/src/test/java/org/jdbi/v3/core/statement/TestParsedSql.java
Labels: feature

#1325 Remove OracleDB support with extreme prejudice.
  CONTRIBUTING.md
  README.md
  RELEASE_NOTES
  bom/pom.xml
  docs/pom.xml
  docs/publish-docs.sh
  oracle12/pom.xml
  oracle12/src/main/java/org/jdbi/v3/oracle12/OracleReturning.java
  oracle12/src/main/java/org/jdbi/v3/oracle12/package.html
  oracle12/src/test/java/org/jdbi/v3/oracle12/OracleDatabaseRule.java
  oracle12/src/test/java/org/jdbi/v3/oracle12/TestGetGeneratedKeysOracle.java
  oracle12/src/test/java/org/jdbi/v3/oracle12/TestOracleReturning.java
  pom.xml
  src/build/ci-code-style.sh
  src/build/ci-doc.sh
  src/build/ci-install.sh
  src/build/ci-test.sh
Labels: cleanup, improvement

#1339 Better handle txIsoLevel.UNKNOWN
  core/src/main/java/org/jdbi/v3/core/Handle.java
  core/src/main/java/org/jdbi/v3/core/Jdbi.java
  core/src/test/java/org/jdbi/v3/core/TestHandle.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/transaction/internal/TransactionDecorator.java
Labels: bug

#1337 Throwables -> Unchecked
  core/src/main/java/org/jdbi/v3/core/OnDemandExtensions.java
  core/src/main/java/org/jdbi/v3/core/internal/Throwables.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedBiFunction.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedCallable.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedFunction.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedSupplier.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/DummyException.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/Sneaky.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/Unchecked.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/ConstructorInstanceFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/StaticMethodInstanceFactory.java
  core/src/test/java/org/jdbi/v3/core/internal/exceptions/SneakyTest.java
  core/src/test/java/org/jdbi/v3/core/internal/exceptions/UncheckedTest.java
  core/src/test/java/org/jdbi/v3/core/statement/TestSqlLoggerCallPoints.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/BridgeMethodHandlerFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/DefaultMethodHandler.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlMethodHandlerFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/config/internal/UseSqlParserImpl.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/config/internal/UseTemplateEngineImpl.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestRegisterRowMapperFactory.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestTransactionAnnotation.java
Labels: cleanup

#1341 add fair warning to MessageFormatTemplateEngine
  core/src/main/java/org/jdbi/v3/core/statement/MessageFormatTemplateEngine.java
  core/src/test/java/org/jdbi/v3/core/statement/TestMessageFormatTemplateEngine.java
Labels: doc

#1359 overdue sqllogger doc
  core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java
  docs/src/adoc/index.adoc
Labels: doc

#1361 Support defining `null` values on templates.
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatements.java
  stringtemplate4/src/test/java/org/jdbi/v3/stringtemplate4/TestDefineNull.java
Labels: improvement

#1362 SqlArrayType: introduce a factory, which simplifies using it nicely
  RELEASE_NOTES
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayType.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayTypeFactory.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayTypeImpl.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayTypes.java
  core/src/main/java/org/jdbi/v3/core/config/Configurable.java
  core/src/test/java/org/jdbi/v3/core/array/TestCustomArrayType.java
Labels: improvement

#1365 Allow AnnotationType.class in place of @AnnotationType for zero-attribute annotation types
  core/src/main/java/org/jdbi/v3/core/argument/internal/TypedValue.java
  core/src/main/java/org/jdbi/v3/core/internal/AnnotationFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/InferredColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/BeanMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/ConstructorMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/FieldMapper.java
  core/src/main/java/org/jdbi/v3/core/qualifier/QualifiedType.java
  core/src/main/java/org/jdbi/v3/core/qualifier/Qualifiers.java
  core/src/main/java/org/jdbi/v3/core/result/ResultBearing.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  core/src/test/java/org/jdbi/v3/core/internal/AnnotationFactoryTest.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestCustomQualifier.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestNVarchar.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestQualifiedType.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestQualifiers.java
  jpa/src/main/java/org/jdbi/v3/jpa/internal/JpaMember.java
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/KotlinSqlStatementCustomizerFactory.kt
  kotlin/src/main/kotlin/org/jdbi/v3/core/kotlin/KotlinMapper.kt
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresQualifiers.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestPostgresQualifiers.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestQualifiedHStore.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/BindFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/ResultReturner.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlUpdateHandler.java
Labels: improvement

#1376 #163 #422 fix jdbi2 docs
  .gitignore
  docs/pom.xml
  docs/src/main/resources/jdbi2/apidocs.zip
  docs/src/main/resources/jdbi2/archive.html
  docs/src/main/resources/jdbi2/community.html
  docs/src/main/resources/jdbi2/dbi_handle_and_statement/index.html
  docs/src/main/resources/jdbi2/faq/index.html
  docs/src/main/resources/jdbi2/five_minute_intro/index.html
  docs/src/main/resources/jdbi2/fluent_queries/index.html
  docs/src/main/resources/jdbi2/getting_jdbi/index.html
  docs/src/main/resources/jdbi2/index.html
  docs/src/main/resources/jdbi2/page10/index.html
  docs/src/main/resources/jdbi2/page11/index.html
  docs/src/main/resources/jdbi2/page12/index.html
  docs/src/main/resources/jdbi2/page2/index.html
  docs/src/main/resources/jdbi2/page3/index.html
  docs/src/main/resources/jdbi2/page4/index.html
  docs/src/main/resources/jdbi2/page5/index.html
  docs/src/main/resources/jdbi2/page6/index.html
  docs/src/main/resources/jdbi2/page7/index.html
  docs/src/main/resources/jdbi2/page8/index.html
  docs/src/main/resources/jdbi2/page9/index.html
  docs/src/main/resources/jdbi2/sql_object_api_argument_binding/index.html
  docs/src/main/resources/jdbi2/sql_object_api_batching/index.html
  docs/src/main/resources/jdbi2/sql_object_api_dml/index.html
  docs/src/main/resources/jdbi2/sql_object_api_queries/index.html
  docs/src/main/resources/jdbi2/sql_object_customizers/index.html
  docs/src/main/resources/jdbi2/sql_object_mixins/index.html
  docs/src/main/resources/jdbi2/sql_object_overview/index.html
Labels: doc

#1371 #605 Cache method-level configs after applying configurers
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java
Labels: cleanup, improvement

#1134 Enables easy registration of kotlin mappers
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMapper.kt
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMapperImpl.kt
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMappers.kt
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMappersImpl.kt
  kotlin-sqlobject/src/test/kotlin/org/jdbi/v3/kotlin/KotlinSqlObjectPluginTest.kt
Labels: feature, improvement
