Repository jdbi/jdbi, pull requests merged in 2019-04, with the labels that each got.

#1461 add `@Unmappable` to disable property mapping of read-only properties like `@Value.Derived`
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/annotation/Unmappable.java
  core/src/main/java/org/jdbi/v3/core/internal/AnnotationFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/ImmutablesPropertiesFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoMapper.java
  core/src/test/java/org/jdbi/v3/core/internal/AnnotationFactoryTest.java
  core/src/test/java/org/jdbi/v3/core/mapper/ImmutablesTest.java
Labels: improvement, integration

#1496 Unmappable: require you to remove column from query; release notes fixup
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoMapper.java
Labels: cleanup

#1479 Remove ExpiringMap dependency; introduce JdbiCache
  RELEASE_NOTES.md
  benchmark/src/main/java/org/jdbi/v3/benchmark/QualifiersBenchmark.java
  core/pom.xml
  core/src/main/java/org/jdbi/v3/core/argument/BeanPropertyArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectFieldArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectMethodArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/QualifiedArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/PojoPropertyArguments.java
  core/src/main/java/org/jdbi/v3/core/config/ConfigRegistry.java
  core/src/main/java/org/jdbi/v3/core/config/JdbiCache.java
  core/src/main/java/org/jdbi/v3/core/config/JdbiCaches.java
  core/src/main/java/org/jdbi/v3/core/internal/EnumStrategies.java
  core/src/main/java/org/jdbi/v3/core/locator/ClasspathSqlLocator.java
  core/src/main/java/org/jdbi/v3/core/mapper/EnumMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/InferredColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/QualifiedColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/immutables/JdbiImmutables.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/BeanMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/ConstructorMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/FieldMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/BeanPropertiesFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/ImmutablesPropertiesFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoTypes.java
  core/src/main/java/org/jdbi/v3/core/qualifier/Qualifiers.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestQualifiers.java
  jpa/src/main/java/org/jdbi/v3/jpa/internal/JpaMember.java
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/KotlinSqlStatementCustomizerFactory.kt
  pom.xml
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/BindFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/ResultReturner.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlUpdateHandler.java
  stringtemplate4/pom.xml
  stringtemplate4/src/main/java/org/jdbi/v3/stringtemplate4/StringTemplateSqlLocator.java
Labels: improvement

#1488 Loosen grammar definitions to treat any non-comment or -parameter as a literal
  .gitignore
  RELEASE_NOTES.md
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/ColonStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/DefineStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/HashStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/SqlScriptLexer.g4
  core/src/test/java/org/jdbi/v3/core/internal/lexer/GrammarTestCase.java
  core/src/test/java/org/jdbi/v3/core/internal/lexer/TestColonGrammar.java
  core/src/test/java/org/jdbi/v3/core/statement/TestColonPrefixSqlParser.java
  core/src/test/java/org/jdbi/v3/core/statement/TestDefinedAttributeTemplateEngine.java
  core/src/test/java/org/jdbi/v3/core/statement/TestHashPrefixSqlParser.java
Labels: bug

#1499 doc edits for latest release
  docs/src/adoc/index.adoc
Labels: doc

#1501 Add a simple Automatic-Module-Name
  .jdbi-parent
  RELEASE_NOTES.md
  benchmark/pom.xml
  bom/pom.xml
  commons-text/pom.xml
  core/pom.xml
  docs/pom.xml
  freemarker/pom.xml
  gson2/pom.xml
  guava/pom.xml
  jackson2/pom.xml
  jodatime2/pom.xml
  jpa/pom.xml
  json/pom.xml
  kotlin-sqlobject/pom.xml
  kotlin/pom.xml
  noparameters/pom.xml
  pom.xml
  postgres/pom.xml
  spring4/pom.xml
  sqlite/pom.xml
  sqlobject/pom.xml
  stringtemplate4/pom.xml
  testing/pom.xml
  vavr/pom.xml
Labels: feature

#1504 Mark postgres driver jar as provided
  RELEASE_NOTES.md
  postgres/pom.xml
Labels: bug

#1500 Detect ambiguous interface multiple inheritance
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestVariousOddities.java
Labels: improvement

#1509 Convenience methods for registering many Immutables types
  core/src/main/java/org/jdbi/v3/core/mapper/immutables/JdbiImmutables.java
Labels: improvement

#1508 RowViewMapper: high-level map operation over RowView
  RELEASE_NOTES.md
  benchmark/pom.xml
  bom/pom.xml
  commons-text/pom.xml
  core/pom.xml
  core/src/main/java/org/jdbi/v3/core/mapper/RowMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/RowViewMapper.java
  core/src/main/java/org/jdbi/v3/core/result/ResultBearing.java
  core/src/main/java/org/jdbi/v3/core/result/RowView.java
  core/src/main/java/org/jdbi/v3/core/result/internal/RowViewImpl.java
  core/src/test/java/org/jdbi/v3/core/mapper/RowViewMapperTest.java
  docs/pom.xml
  freemarker/pom.xml
  gson2/pom.xml
  guava/pom.xml
  jackson2/pom.xml
  jodatime2/pom.xml
  jpa/pom.xml
  json/pom.xml
  kotlin-sqlobject/pom.xml
  kotlin/pom.xml
  noparameters/pom.xml
  policy/pom.xml
  pom.xml
  postgres/pom.xml
  spring4/pom.xml
  sqlite/pom.xml
  sqlobject/pom.xml
  stringtemplate4/pom.xml
  testing/pom.xml
  vavr/pom.xml
Labels: feature

#1517 Avoid SqlBatch customizer null argument
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/statement/PreparedBatch.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlBatchWithCustomizer.java
Labels: bug
