Repository jdbi/jdbi, pull requests merged in 2019-01, with the labels that each got.

#1378 fix #1377: BindList conditionals with null and StringTemplate
  freemarker/src/test/java/org/jdbi/v3/freemarker/BindListNullPostgresTest.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/BindList.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/BindListFactory.java
  stringtemplate4/src/test/java/org/jdbi/v3/sqlobject/BindListNullPostgresTest.java
  stringtemplate4/src/test/java/org/jdbi/v3/sqlobject/BindListNullTest.java
  stringtemplate4/src/test/java/org/jdbi/v3/sqlobject/BindListTest.java
Labels: improvement

#1360 TimestampedConfig to customize timezone
  RELEASE_NOTES
  docs/src/adoc/index.adoc
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/Timestamped.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/TimestampedConfig.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/TimestampedFactory.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestTimestamped.java
Labels: cleanup, doc, improvement

#1396 Polish QualifiedType and related code
  core/src/main/java/org/jdbi/v3/core/argument/Arguments.java
  core/src/main/java/org/jdbi/v3/core/argument/QualifiedArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/TypedValue.java
  core/src/main/java/org/jdbi/v3/core/config/Configurable.java
  core/src/main/java/org/jdbi/v3/core/generic/GenericType.java
  core/src/main/java/org/jdbi/v3/core/mapper/ColumnMappers.java
  core/src/main/java/org/jdbi/v3/core/mapper/InferredColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/Mappers.java
  core/src/main/java/org/jdbi/v3/core/mapper/QualifiedColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/BeanMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/ConstructorMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/FieldMapper.java
  core/src/main/java/org/jdbi/v3/core/qualifier/QualifiedType.java
  core/src/main/java/org/jdbi/v3/core/result/ResultBearing.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestCustomQualifier.java
  core/src/test/java/org/jdbi/v3/core/qualifier/TestNVarchar.java
  core/src/test/java/org/jdbi/v3/core/statement/StatementContextTest.java
  jpa/src/main/java/org/jdbi/v3/jpa/JpaMapper.java
  jpa/src/main/java/org/jdbi/v3/jpa/internal/JpaMember.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestQualifiedHStore.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/BindFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/MapToFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/ResultReturner.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlQueryHandler.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlUpdateHandler.java
Labels: cleanup, improvement

#1358 Separate json concerns
  docs/src/adoc/index.adoc
  gson2/src/main/java/org/jdbi/v3/gson2/GsonJsonMapper.java
  gson2/src/test/java/org/jdbi/v3/gson2/TestGson2Plugin.java
  jackson2/src/main/java/org/jdbi/v3/jackson2/Jackson2Plugin.java
  jackson2/src/main/java/org/jdbi/v3/jackson2/JacksonJsonMapper.java
  jackson2/src/test/java/org/jdbi/v3/jackson2/TestJackson2Plugin.java
  json/pom.xml
  json/src/main/java/org/jdbi/v3/json/JsonConfig.java
  json/src/main/java/org/jdbi/v3/json/JsonMapper.java
  json/src/main/java/org/jdbi/v3/json/JsonPlugin.java
  json/src/main/java/org/jdbi/v3/json/internal/AbstractJsonPlugin.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonArgumentFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonColumnMapperFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/StubJsonMapper.java
  json/src/test/java/org/jdbi/v3/json/AbstractJsonMapperTest.java
  json/src/test/java/org/jdbi/v3/json/JsonPluginTest.java
  json/src/test/java/org/jdbi/v3/json/StubJsonMapperTest.java
  postgres/src/main/java/org/jdbi/v3/postgres/JsonArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresPlugin.java
Labels: improvement

#1386 fix null byte array typing
  core/src/main/java/org/jdbi/v3/core/argument/Arguments.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/array/SqlArrayTypes.java
  core/src/main/java/org/jdbi/v3/core/internal/IterableLike.java
  core/src/test/java/org/jdbi/v3/core/array/ByteArrayTest.java
Labels: bug

#1368 Introduce defineBinds, which uses the bindings to create definitions for templates
  RELEASE_NOTES
  core/src/main/java/org/jdbi/v3/core/argument/ArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/BeanPropertyArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/DelegatingArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/MapArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/NamedArgumentFinder.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/strategies/LoggableSetNullOrBinderArgument.java
  core/src/main/java/org/jdbi/v3/core/statement/BaseStatement.java
  core/src/main/java/org/jdbi/v3/core/statement/Binding.java
  core/src/main/java/org/jdbi/v3/core/statement/DefineNamedBindingsStatementCustomizer.java
  core/src/main/java/org/jdbi/v3/core/statement/PreparedBatch.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  core/src/main/java/org/jdbi/v3/core/statement/StatementCustomizer.java
  core/src/test/java/org/jdbi/v3/core/statement/TestDefineNamedBindings.java
  docs/src/adoc/index.adoc
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/DefineNamedBindings.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/DefineNamedBindingsFactory.java
  stringtemplate4/src/test/java/org/jdbi/v3/core/statement/TestDefineNamedBindingsST.java
Labels: feature

#1398 jdbi.org favicon
  docs/src/adoc/favicon.ico
  docs/src/adoc/images/favicon.png
  docs/src/adoc/index-docinfo.html
  docs/src/adoc/index.adoc
Labels: doc, improvement

#1375 #1374 explain BindList a bit more
  docs/src/adoc/index.adoc
Labels: doc

#1409 Remove LoggableToStringOrNPEArgument
  core/src/main/java/org/jdbi/v3/core/argument/EnumArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/JavaTimeZoneIdArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/NullArgument.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectArgument.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/strategies/AbstractLoggableArgument.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/strategies/LoggableBinderArgument.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/strategies/LoggableSetObjectArgument.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/strategies/LoggableToStringOrNPEArgument.java
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  postgres/src/main/java/org/jdbi/v3/postgres/DurationArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/HStoreArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/InetArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/JavaTimeArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/PeriodArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/TypedEnumArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/UUIDArgumentFactory.java
  sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java
Labels: cleanup

#1432 Fix enum case insensitive matching to actually work
  core/src/main/java/org/jdbi/v3/core/mapper/EnumMapper.java
Labels: improvement

#1423 fix #1422
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/TimestampedFactory.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/MockClock.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestInheritedAnnotations.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/customizer/internal/TestTimestamped.java
Labels: bug

#1407 WIP: document qualified types
  docs/src/adoc/index.adoc
Labels: doc

#1439 Keep using String.format instead of MessageFormat
  core/src/main/java/org/jdbi/v3/core/mapper/GenericMapMapperFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/MaxRowsFactory.java
Labels: cleanup

#1437 json: remove use of StatementContext, simplify mapper / argument lambdas
  core/src/main/java/org/jdbi/v3/core/result/UnableToProduceResultException.java
  core/src/main/java/org/jdbi/v3/core/statement/StatementException.java
  core/src/main/java/org/jdbi/v3/core/statement/UnableToCreateStatementException.java
  gson2/src/main/java/org/jdbi/v3/gson2/GsonJsonMapper.java
  jackson2/src/main/java/org/jdbi/v3/jackson2/JacksonJsonMapper.java
  json/src/main/java/org/jdbi/v3/json/JsonConfig.java
  json/src/main/java/org/jdbi/v3/json/JsonMapper.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonArgumentFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonColumnMapperFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/UnimplementedJsonMapper.java
  json/src/test/java/org/jdbi/v3/json/JsonPluginTest.java
Labels: improvement

#1411 Fix handle close + transaction handling errors
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/Handle.java
  core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java
  core/src/test/java/org/jdbi/v3/core/TestHandle.java
  core/src/test/java/org/jdbi/v3/core/transaction/TestTransactions.java
Labels: bug

#1442 Fix remnant legacy related to #1388
  freemarker/src/main/java/org/jdbi/v3/freemarker/internal/UseFreemarkerSqlLocatorImpl.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/internal/SqlAnnotations.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/locator/AnnotationSqlLocator.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/locator/internal/UseClasspathSqlLocatorImpl.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestUseClasspathSqlLocator.java
  sqlobject/src/test/resources/org/jdbi/v3/sqlobject/TestUseClasspathSqlLocator$Blanks/empty.sql
  stringtemplate4/src/main/java/org/jdbi/v3/stringtemplate4/internal/UseStringTemplateSqlLocatorImpl.java
Labels: bug, cleanup
