Repository jdbi/jdbi, pull requests merged in 2019-02, with the labels that each got.

#1443 DefineNamedBindings: use a proxy Statement rather than inspecting for `NullArgument`
  core/src/main/java/org/jdbi/v3/core/argument/ArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/Unchecked.java
  core/src/main/java/org/jdbi/v3/core/statement/DefineNamedBindingsStatementCustomizer.java
  core/src/test/java/org/jdbi/v3/core/statement/TestDefineNamedBindings.java
  docs/src/adoc/index.adoc
Labels: improvement

#1425 add support for postgres custom types
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/array/ArrayColumnMapper.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedBiConsumer.java
  core/src/main/java/org/jdbi/v3/core/internal/exceptions/Unchecked.java
  docs/src/test/java/jdbi/doc/KotlinPluginTest.kt
  postgres/src/main/java/org/jdbi/v3/postgres/PGobjectArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/PGobjectColumnMapperFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresPlugin.java
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresTypes.java
  postgres/src/test/java/org/jdbi/v3/postgres/FooBarPGType.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestPostgresTypes.java
Labels: feature, help wanted

#1448 Post-merge refactor #1443
  core/src/main/java/org/jdbi/v3/core/statement/DefineNamedBindingsStatementCustomizer.java
Labels: cleanup

#1447 Basic high availability docs
  docs/src/adoc/index.adoc
Labels: doc

#1450 RowView: add support for columns with QualifiedType
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/result/RowView.java
  core/src/test/java/org/jdbi/v3/core/result/TestRowView.java
Labels: improvement

#1455 DefineNamedBindings: check getConnction works (e.g. sql array uses it)
  core/src/main/java/org/jdbi/v3/core/statement/DefineNamedBindingsStatementCustomizer.java
  core/src/test/java/org/jdbi/v3/core/statement/TestDefineNamedBindings.java
Labels: bug

#1457 pass the type arg to gson for serialization
  gson2/src/main/java/org/jdbi/v3/gson2/GsonJsonMapper.java
  gson2/src/test/java/org/jdbi/v3/gson2/TestGson2Plugin.java
Labels: improvement

#1452 Split SqlObject classpath locator to it's own class
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/locator/SqlObjectClasspathSqlLocator.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/locator/internal/UseClasspathSqlLocatorImpl.java
Labels: feature

#1465 Fixed platform-dependent test
  core/src/test/java/org/jdbi/v3/core/statement/TestMessageFormatTemplateEngine.java
  postgres/pom.xml
  postgres/src/test/java/org/jdbi/v3/TestStatementsTimeout.java
  postgres/src/test/java/org/jdbi/v3/postgres/PostgresDbRule.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestPostgresTypes.java
  testing/src/main/java/org/jdbi/v3/testing/EmbeddedPostgresJdbiRule.java
  testing/src/main/java/org/jdbi/v3/testing/JdbiRule.java
Labels: cleanup

#1469 Fix Immutables byte[] properties
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/ImmutablesPropertiesFactory.java
  core/src/test/java/org/jdbi/v3/core/mapper/ImmutablesTest.java
Labels: bug

#1445 Extend qualtyp api for collection<class<>>
  core/src/main/java/org/jdbi/v3/core/argument/ObjectFieldArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectMethodArguments.java
  core/src/main/java/org/jdbi/v3/core/internal/EnumStrategies.java
  core/src/main/java/org/jdbi/v3/core/mapper/InferredColumnMapperFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/ConstructorMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/FieldMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/BeanPropertiesFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/ImmutablesPropertiesFactory.java
  core/src/main/java/org/jdbi/v3/core/qualifier/QualifiedType.java
  jpa/src/main/java/org/jdbi/v3/jpa/internal/JpaMember.java
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/KotlinSqlStatementCustomizerFactory.kt
  kotlin/src/main/kotlin/org/jdbi/v3/core/kotlin/KotlinMapper.kt
  kotlin/src/main/kotlin/org/jdbi/v3/core/kotlin/internal/KotlinPropertyArguments.kt
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/internal/BindFactory.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/ResultReturner.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlUpdateHandler.java
Labels: improvement

#1468 Change one of the Travis builds to `fr_FR` so we don't inadvertently introduce locale deps
  .travis.yml
Labels: WIP

#1475 Resolve generic method parameters from SQL object superclass
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/CustomizingStatementHandler.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlObject.java
  sqlobject/src/test/resources/org/jdbi/v3/sqlobject/TestSqlObject$ExtendGenericDaoWithExplicitParameter/batchInsert.sql
  sqlobject/src/test/resources/org/jdbi/v3/sqlobject/TestSqlObject$ExtendGenericDaoWithExplicitParameter/list.sql
Labels: bug

#1476 suppress exception if Statement close method raises
  core/src/main/java/org/jdbi/v3/core/result/ResultProducers.java
Labels: bug
