Repository jdbi/jdbi, pull requests merged in 2019-03, with the labels that each got.

#1449 getObject/setObject factories for LocalDate et al
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/argument/SetObjectArgumentFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/GetObjectColumnMapperFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/JavaTimeArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/JavaTimeMapperFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/UUIDArgumentFactory.java
Labels: feature

#1480 Remove shading once and for all.
  RELEASE_NOTES.md
  core/pom.xml
  core/src/main/antlr3/org/jdbi/v3/core/internal/lexer/FormatterStatementLexer.g
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/ColonStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/DefineStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/HashStatementLexer.g4
  core/src/main/antlr4/org/jdbi/v3/core/internal/lexer/SqlScriptLexer.g4
  core/src/main/java/org/jdbi/v3/core/internal/SqlScriptParser.java
  core/src/main/java/org/jdbi/v3/core/locator/ClasspathSqlLocator.java
  core/src/main/java/org/jdbi/v3/core/statement/ColonPrefixSqlParser.java
  core/src/main/java/org/jdbi/v3/core/statement/DefinedAttributeTemplateEngine.java
  core/src/main/java/org/jdbi/v3/core/statement/HashPrefixSqlParser.java
  core/src/main/java/org/jdbi/v3/core/statement/Script.java
  core/src/main/java/org/jdbi/v3/core/statement/internal/ErrorListener.java
  core/src/test/java/org/jdbi/v3/core/internal/lexer/GrammarTestCase.java
  core/src/test/java/org/jdbi/v3/core/internal/lexer/TestColonGrammar.java
  core/src/test/java/org/jdbi/v3/core/internal/lexer/TestPrintfGrammar.java
  pom.xml
  stringtemplate4/pom.xml
Labels: cleanup

#1481 Replace synchronized WeakHashMap with ConcurrentHashMap
  core/src/main/java/org/jdbi/v3/core/config/ConfigRegistry.java
Labels: improvement

#1335 Remove Guava reflection code, use GeAnTyRef instead!
  core/pom.xml
  core/src/main/java/org/jdbi/v3/core/generic/GenericTypes.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/Preconditions.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/Reflection.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/TypeCapture.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/TypeParameter.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/TypeResolver.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/TypeToken.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/TypeVisitor.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/Types.java
  core/src/main/java/org/jdbi/v3/lib/internal/com_google_guava/guava/v21_0/package.html
  pom.xml
  vavr/src/main/java/org/jdbi/v3/vavr/VavrCollectorFactory.java
  vavr/src/main/java/org/jdbi/v3/vavr/VavrGenericMapUtil.java
Labels: dependency

#1486 Add simple support for Jackson `@JsonView`
  RELEASE_NOTES.md
  jackson2/src/main/java/org/jdbi/v3/jackson2/Jackson2Config.java
  jackson2/src/main/java/org/jdbi/v3/jackson2/JacksonJsonMapper.java
  jackson2/src/test/java/org/jdbi/v3/jackson2/TestJackson2Plugin.java
Labels: improvement

#1491 assertj-guava: update to avoid ranged dependency on assertj-core
  pom.xml
Labels: bug

#1492 StringTemplate: fix test to properly shut down executor and actually look at the results
  stringtemplate4/src/test/java/org/jdbi/v3/stringtemplate4/TestStringTemplateLoading.java
Labels: improvement
