Repository jdbi/jdbi, pull requests merged in 2020-06, with the labels that each got.

#1711 Postgres: add simple LargeObject support
  RELEASE_NOTES.md
  docs/src/adoc/index.adoc
  postgres/pom.xml
  postgres/src/main/java/org/jdbi/v3/postgres/BlobInputStreamArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/BlobInputStreamColumnMapperFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/ClobReaderArgumentFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/ClobReaderColumnMapperFactory.java
  postgres/src/main/java/org/jdbi/v3/postgres/DeleteLob.java
  postgres/src/main/java/org/jdbi/v3/postgres/LargeObjectException.java
  postgres/src/main/java/org/jdbi/v3/postgres/PgLobApi.java
  postgres/src/main/java/org/jdbi/v3/postgres/PgLobApiImpl.java
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresPlugin.java
  postgres/src/main/java/org/jdbi/v3/postgres/PostgresTypes.java
  postgres/src/main/java/org/jdbi/v3/postgres/internal/DeleteLobCustomizerFactory.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestLobStream.java
Labels: feature

#1714 Fix package declaration for RegisterKotlinMappers
  RELEASE_NOTES.md
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMapper.kt
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMappers.kt
  kotlin-sqlobject/src/main/kotlin/org/jdbi/v3/sqlobject/kotlin/RegisterKotlinMappersImpl.kt
Labels: bug

#1716 Update: add `one` helper method
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/statement/Update.java
Labels: feature

#1717 Correct transaction docs
  docs/src/adoc/index.adoc
Labels: doc

#1718 remove moot todos
  core/src/main/java/org/jdbi/v3/core/argument/Arguments.java
  core/src/main/java/org/jdbi/v3/core/collector/JdbiCollectors.java
  core/src/main/java/org/jdbi/v3/core/mapper/ColumnMappers.java
Labels: cleanup

#1721 Array: fix repeated binding of Iterable types
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java
  postgres/src/test/java/org/jdbi/v3/postgres/TestSqlArrays.java
Labels: bug
