Repository jdbi/jdbi, pull requests merged in 2021-04, with the labels that each got.

#1817 Add some documentation about escaping ST templates
  docs/src/adoc/index.adoc
Labels: doc

#1827 Add some documentation about result lifecycle
  docs/src/adoc/index.adoc
Labels: doc

#1828 Add a simple Slf4J SQL statement logger
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/statement/Slf4JSqlLogger.java
  docs/src/adoc/index.adoc
Labels: feature

#1829 Add a new RollbackOnlyTransactionHandler
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/transaction/RollbackOnlyTransactionHandler.java
  core/src/test/java/org/jdbi/v3/core/transaction/RollbackOnlyTransactionHandlerTest.java
Labels: feature

#1833 Update Spring baseline with jdk16 fixes
  pom.xml
  spring5/pom.xml
  spring5/src/test/java/org/jdbi/v3/spring5/TestVersion.java
Labels: improvement

#1835 update geantyref to 1.3.11
  pom.xml
Labels: improvement

#1842 Add a new Alpha annotation
  core/src/main/java/org/jdbi/v3/meta/Alpha.java
Labels: feature

#1844 Note @Alpha in the docs
  RELEASE_NOTES.md
  docs/src/adoc/index.adoc
Labels: doc

#1850 Nuke Spring 4, which is EOL
  bom/pom.xml
  docs/pom.xml
  pom.xml
  spring4/pom.xml
  spring4/src/main/java/org/jdbi/v3/spring4/JdbiFactoryBean.java
  spring4/src/main/java/org/jdbi/v3/spring4/JdbiUtil.java
  spring4/src/main/java/org/jdbi/v3/spring4/SpringConnectionFactory.java
  spring4/src/main/java/org/jdbi/v3/spring4/package.html
Labels: cleanup

#1855 Call out Java 8 caffeine compatibility a bit more prominently in the release notes
  RELEASE_NOTES.md
Labels: doc

#1857 Correct case in docs link
  docs/src/adoc/index.adoc
Labels: bug, doc

#1861 Update docs to reflect bindlist update query
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/customizer/BindList.java
Labels: doc

#1862 asciidoctor 2.1.0
  pom.xml
Labels: improvement

#1865 Actually deploy Spring5 artifacts
  RELEASE_NOTES.md
  spring5/pom.xml
Labels: bug

#1863 Add one-time init methods to row and column mappers
  core/src/main/java/org/jdbi/v3/core/codec/Codec.java
  core/src/main/java/org/jdbi/v3/core/codec/CodecFactory.java
  core/src/main/java/org/jdbi/v3/core/mapper/ColumnMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/ColumnMappers.java
  core/src/main/java/org/jdbi/v3/core/mapper/RowMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/RowMappers.java
  core/src/test/java/org/jdbi/v3/core/mapper/TestMapperInit.java
Labels: feature

#1866 Add spring5 to the bom
  bom/pom.xml
Labels: bug
