Repository jdbi/jdbi, pull requests merged in 2022-10, with the labels that each got.

#2128 fix(generator): return latest supported SourceVersion instead of 8
  RELEASE_NOTES.md
  generator/src/main/java/org/jdbi/v3/generator/GenerateSqlObjectProcessor.java
Labels: feature, improvement

#2129 Replace `@Unmappable` with `@JdbiProperty` and support skipping binding arguments
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/annotation/JdbiProperty.java
  core/src/main/java/org/jdbi/v3/core/annotation/internal/JdbiAnnotations.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectFieldArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/ObjectMethodArguments.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/NamedArgumentFinderFactory.java
  core/src/main/java/org/jdbi/v3/core/argument/internal/PojoPropertyArguments.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/FieldMapper.java
  core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/PojoMapper.java
  core/src/main/java/org/jdbi/v3/core/result/ResultSetResultIterator.java
  core/src/test/java/org/jdbi/v3/core/mapper/FreeBuildersTest.java
  core/src/test/java/org/jdbi/v3/core/mapper/ImmutablesTest.java
  core/src/test/java/org/jdbi/v3/core/mapper/JdbiPropertyTest.java
  core/src/test/java/org/jdbi/v3/core/mapper/UnmappableTest.java
  docs/src/adoc/index.adoc
  kotlin/src/main/kotlin/org/jdbi/v3/core/kotlin/KotlinMapper.kt
  kotlin/src/test/kotlin/org/jdbi/v3/core/kotlin/KotlinUnmappableTest.kt
Labels: feature

#2146 Add ResultIterable.withIterator and useIterator
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/result/IteratorCallback.java
  core/src/main/java/org/jdbi/v3/core/result/IteratorConsumer.java
  core/src/main/java/org/jdbi/v3/core/result/ResultIterable.java
Labels: feature

#2149 hsqldb 2.7.1
  internal/build/pom.xml
Labels: dependency
