Repository jdbi/jdbi, pull requests merged in 2023-06, with the labels that each got.

#2377 Implement @RegisterCollector with tests and short doc
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/collector/SimpleCollectorFactory.java
  docs/src/adoc/index.adoc
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/config/RegisterCollector.java
  sqlobject/src/main/java/org/jdbi/v3/sqlobject/config/internal/RegisterCollectorImpl.java
  sqlobject/src/test/java/org/jdbi/v3/sqlobject/config/RegisterCollectorTest.java
Labels: feature

#2404 PreparedBatch c'tor fix
  RELEASE_NOTES.md
  core/src/main/java/org/jdbi/v3/core/statement/PreparedBatch.java
Labels: backport-jdk8

#2423 generator: add tests covering Object method overrides
  generator/src/test/java/org/jdbi/v3/generator/NonpublicSubclassTest.java
Labels: improvement

#2420 Json plugin: do json type resolution during prepare stage
  RELEASE_NOTES.md
  gson2/src/main/java/org/jdbi/v3/gson2/GsonJsonMapper.java
  jackson2/src/main/java/org/jdbi/v3/jackson2/JacksonJsonMapper.java
  json/src/main/java/org/jdbi/v3/json/JsonMapper.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonArgumentFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/JsonColumnMapperFactory.java
  json/src/main/java/org/jdbi/v3/json/internal/UnimplementedJsonMapper.java
  json/src/test/java/org/jdbi/v3/json/JsonPluginTest.java
  json/src/test/java/org/jdbi/v3/json/StubJsonMapperTest.java
  moshi/src/main/java/org/jdbi/v3/moshi/MoshiJsonMapper.java
Labels: improvement
